### ISSUE TITLE
メールボックスでThread内に２通以上の未読メールがある場合，最初のメールしかSlackへ通知されない

### ISSUE THREAD

**Issue by takanakahiko** [bannzai/connpass-notification#8]
## 問題

現在，メールボックスでThread内に２通以上の未読メールがある場合，最初のメールしかSlackへ通知されないです．

「メールボックスでThread内に２通以上の未読メールがある場合」の例 : 

![image](https://user-images.githubusercontent.com/10114717/54082371-0addc580-4358-11e9-95df-03d8cb94ea14.png)

スレッド単位で処理していることが原因だと思います．

## 提案

前提として

- メールボックス内にスレッドがある
- スレッド内にメッセージがある

となっています．

現在の処理を確認すると．

1. 未読スレッドを探す
2. スレッド内の１つめのメールを通知する
3. スレッドを既読にする

といった流れとなっています．
ここで，2つめ以降のメールは無視されてしまいます．

そこで，提案として

1. 未読スレッド(スレッド内で一つでも未読メールがある場合は未読スレッド扱いになります)を探す
2. スレッド内のメールをforループ
 a. 未読メールを探す
 b.  メールの内容を通知する
3. スレッドを既読にする

といった処理に変更することで，２つめ以降も漏れなく通知がされると考えられます．

**Comment by bannzai** [comment]
なるほど。これって例えば同じ人が同じイベントに2回参加した場合はGmail内ではスレッドに溜まっていくって感じであってそうですか？

スレッド内のメールを全部回すのは特に害もなさそうだし網羅できそうで良さそうだなと思っています！

**Comment by takanakahiko** [comment]
メールタイトルが同じ(または `Re:` などの軽微な差 )だと同じスレッドになります．
普通は，返信等が一つのスレッドになっているので追いやすくなるとかのメリットがあります．

しかし，今回のようなサービスからの通知メールはタイトルが同じという理由で一つのスレッドにまとめられてしまう場合があります．

ですから，同じ人でなくても「タイトルが同じであれば」同じスレッドに入る仕様になっています．
(上の画像例はそれぞれ違う参加者です)
